// Noetec.
// Copyright (c) 2026 The Noetec Authors.
// See the AUTHORS file for the full list of contributors.
// AGPLv3 License: https://www.gnu.org/licenses/agpl-3.0.html

// Golden round-trip tests for the markdown parser/serializer against the
// normative spec docs/specs/file-format.md (format version 1).
//
// For each fixture under test/fixtures/format/v1/:
//   1. Read the file bytes.
//   2. Normalize CRLF/CR to LF (spec §2).
//   3. Strip the frontmatter block (spec §3.1, §5) to obtain the content body.
//   4. Parse the body via MarkdownSystem.parseMarkdown.
//   5. Serialize the resulting blocks via MarkdownSystem.serializeBlocks.
//   6. Assert the serialized output equals the normalized body byte-for-byte.
//
// Round-trip is semantic for inline content; it is byte-stable only when the
// fixture itself is in canonical (serializer-emitted) form, per spec §6.
// The `modified` frontmatter field is non-deterministic and therefore not
// covered here; see page_frontmatter_roundtrip_test.dart for frontmatter
// handling.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:noetec/service/id_service.dart';
import 'package:noetec/systems/markdown_system/markdown_system.dart';

class _FakeIdService implements IIdService {
  int _counter = 0;
  @override
  String generateId() => 'generated-id-${_counter++}';
}

/// Reads a fixture file, normalizes line endings to LF, and returns the
/// content body (i.e. the file minus any leading frontmatter block).
///
/// Per spec §5, the body is what remains after the opening `---`, the YAML
/// frontmatter, the closing `---`, and the single blank separator line.
String _extractBody(String fixturePath) {
  final raw = File(fixturePath).readAsStringSync();
  // Spec §2: normalize CRLF / CR to LF.
  final normalized = raw.replaceAll('\r\n', '\n').replaceAll('\r', '\n');

  if (!normalized.startsWith('---\n')) return normalized;

  final closingIndex = normalized.indexOf('\n---\n', 4);
  if (closingIndex == -1) return normalized;

  var bodyStart = closingIndex + '\n---\n'.length;
  // Spec §3.1: a single blank line after the closing delimiter is a separator.
  if (bodyStart < normalized.length && normalized[bodyStart] == '\n') {
    bodyStart += 1;
  }
  return normalized.substring(bodyStart);
}

void main() {
  late MarkdownSystem markdownSystem;

  setUp(() {
    markdownSystem = MarkdownSystem(_FakeIdService());
  });

  // Well-formed fixtures whose body is in canonical serializer-emitted form.
  // Each must round-trip byte-for-byte through parse → serialize.
  const wellFormedFixtures = [
    'welcome',
    'nested-blocks',
    'inline-formatting',
    'links',
    'windows-line-endings',
  ];

  group('Markdown golden round-trip (format v1) —', () {
    for (final name in wellFormedFixtures) {
      test('$name: parse → serialize is byte-for-byte stable', () {
        final path = 'test/fixtures/format/v1/$name.md';
        final expectedBody = _extractBody(path);

        final blocks = markdownSystem.parseMarkdown(expectedBody);
        final serialized = markdownSystem.serializeBlocks(blocks);

        expect(
          serialized,
          expectedBody,
          reason:
              'Round-trip divergence for fixture "$name".\n'
              'Expected body:\n$expectedBody\n'
              'Serialized:\n$serialized',
        );
      });
    }

    test('missing-frontmatter: entire file is treated as content body', () {
      const path = 'test/fixtures/format/v1/missing-frontmatter.md';
      final body = _extractBody(path);

      // The fixture has no frontmatter, so _extractBody returns the full
      // normalized file. Parsing it as markdown must succeed (spec §3.4.1)
      // and produce at least one block per top-level markdown chunk.
      final blocks = markdownSystem.parseMarkdown(body);

      expect(blocks, isNotEmpty);
      // No block id may come from a directive (the fixture has none); each
      // id is freshly generated by the fake id service.
      for (final block in blocks) {
        expect(block.id, startsWith('generated-id-'));
      }
    });
  });
}
