// Noetec.
// Copyright (c) 2026 The Noetec Authors.
// See the AUTHORS file for the full list of contributors.
// AGPLv3 License: https://www.gnu.org/licenses/agpl-3.0.html

// ignore_for_file: avoid_print
import 'dart:io';

/// Installs the git pre-commit hook into the repository's real hooks
/// directory (linked-worktree safe).
///
/// We deliberately do NOT use `git_hooks`'s `CreateHooks.copyFile`: it writes
/// to `<root>/.git/hooks/`, which fails in a linked worktree because `.git`
/// is a *file* (a `gitdir:` pointer), not a directory. Agents work in linked
/// worktrees (`multica repo checkout`), so we resolve the true hooks path via
/// git (`git rev-parse --git-path hooks`) and write the hook wrapper directly.
///
/// The hook wrapper runs `dart scripts/git_hooks.dart pre-commit`, which does
/// format + scoped analyze + copyright check on staged files.
Future<void> main() async {
  print('🔄 Setup Git hooks');

  final hooksDir = await _gitPath('hooks');
  if (hooksDir == null) {
    print('❌ Not a git repository — no hooks installed.');
    exit(1);
  }

  final hookFile = File('$hooksDir/pre-commit');
  await hookFile.writeAsString(_hookWrapper);
  // Make executable (no-op on Windows).
  await Process.run('chmod', ['+x', hookFile.path]);

  print('✅ Git pre-commit hook installed at ${hookFile.path}');
  print('   Run `dart run scripts/setup_project.dart` to reinstall/update it.');
}

/// Resolves a git path via `git rev-parse --git-path <name>`.
///
/// Works in both a normal clone (returns `.git/<name>`) and a linked worktree
/// (returns the common git dir's `<name>`). Returns `null` outside a repo.
Future<String?> _gitPath(String name) async {
  final result = await Process.run('git', ['rev-parse', '--git-path', name]);
  if (result.exitCode != 0) return null;
  return (result.stdout as String).trim();
}

const _hookWrapper = '''
#!/bin/sh
# Noetec pre-commit hook. Installed by `dart run scripts/setup_project.dart`.
# Do not edit this file — regenerate it with the command above.
hookName=\$(basename "\$0")
if command -v dart >/dev/null 2>&1; then
  dart scripts/git_hooks.dart "\$hookName"
  exit \$?
else
  echo "Cannot find dart in PATH"
  exit 1
fi
''';
